language: php

php:
  - "5.3"
  - "5.4"
  - "5.5"

before_script:
  ## PHP_CodeSniffer
  - pear install pear/PHP_CodeSniffer
  - phpenv rehash
  ## PHP Copy/Paste Detector
  - curl -o phpcpd.phar https://phar.phpunit.de/phpcpd.phar
  ## PHP Mess Detector
  - pear config-set preferred_state beta
  - printf "\n" | pecl install imagick
  - pear channel-discover pear.phpmd.org
  - pear channel-discover pear.pdepend.org
  - pear install --alldeps phpmd/PHP_PMD
  - phpenv rehash
  ## PHPLOC
  - curl -o phploc.phar https://phar.phpunit.de/phploc.phar

script:
  ## PHP_CodeSniffer
  - phpcs --report=emacs --standard=PSR1 .
  - phpcs --report=emacs --standard=PSR2 .
  ## PHP Copy/Paste Detector
  - php phpcpd.phar --verbose .
  ## PHP Mess Detector
  - phpmd . text cleancode
  - phpmd . text codesize
  - phpmd . text controversial
  - phpmd . text design
  - phpmd . text naming
  - phpmd . text unusedcode
  ## PHPLOC
  - php phploc.phar .
  ## PHPUNIT
  - phpunit test

notifications:
  email:
    sourcespeak@phor.net
